### ISSUE TITLE
Implement AudioRenderCapacity

### ISSUE THREAD

**Issue by b-ma** [ircam-ismm/node-web-audio-api#122]

**Comment by orottier** [comment]
Sorry I should have mentioned this earlier but I just remember hoch told me this API is not likely to actually land in the browsers due to security concerns.
I would say it is still nice to have for us because the concerns do not apply to node/rust applications, just for browser sandboxes. Since everything is nicely spec'd and all it would be a shame to not have it.

**Comment by b-ma** [comment]
Thanks for the info, and agreed this is a nice to have anyway!
