### ISSUE TITLE
Missing nativeBinding for platform: node-web-audio-api.linux-arm64-gnu.node

### ISSUE THREAD

**Issue by bthj** [ircam-ismm/node-web-audio-api#19]
Hi - when running a Node app, depending on `node-web-audio-api`, in a container (podman, hosted on apple m1), the following error is printed:

```
Error: Cannot find module './node-web-audio-api.linux-arm64-gnu.node'
Require stack:
- /app/node_modules/kromosynth/node_modules/node-web-audio-api/index.cjs
- /app/node_modules/kromosynth/node_modules/node-web-audio-api/index.mjs
...
```

In the [currently published package](https://www.npmjs.com/package/node-web-audio-api?activeTab=code), `node-web-audio-api.linux-arm64-gnu.node` is not present, which is referenced on line 58 in `index.cjs`. How can that platform be added to the build configuration?

**Comment by b-ma** [comment]
Hey, actually the linux build is quite a mess for now as I didn't manage to make it work in the github build action. If I remember will this was mainly due to the fact that the provided virtual machines don't have any soundcard and therefore alsa requirement failed in some way. 

So what I do for now according to the linux versions is to:
- build the x64 gnu in a docker container on my own machine, an Intel macbook
- build the arm gnueabihf version on a "real" raspberry pi (32bits, 64bit system is missing but could be quite easily fixed on my side)

I tried quite hard to cross-compile everything in docker images to support more platforms, but miserably failed. If you have some knowledge about cross-compilation, i.e. how to create such docker image and how to launch the cross-compilation from cargo, it would be really appreciated. But for now I'm afraid I don't have any much more elegant solution than building the lib manually as described in the [README](https://github.com/ircam-ismm/node-web-audio-api#manual-build).

(side-note: there may be some lights in a foreseeable future, as it is possible I will have access to more machines and architectures, but I prefer not to guarantee anything for now)

**Comment by bthj** [comment]
On a virtual machine running an [arm image](https://cdimage.ubuntu.com/jammy/daily-live/current/) (in VMware Fusion) I was able to build an arm version: 
[node-web-audio-api.linux-arm64-gnu.node.zip](https://github.com/ircam-ismm/node-web-audio-api/files/11072994/node-web-audio-api.linux-arm64-gnu.node.zip)

- before i had to `sudo apt install librust-alsa-sys-dev` on the build machine (the instructions in the [Manual Build](https://github.com/ircam-ismm/node-web-audio-api#manual-build) section didn't work for me but those in the [Running the Examples](https://github.com/ircam-ismm/node-web-audio-api#manual-build) section did). I'd be happy to make a new build when needed (e.g. for new versions).

For use in the container, I had to apt-get libasound2 and create an `asound.conf` file containing:
```
pcm.!default {
    type plug
    slave.pcm "null"
}
```
and in the Dockerfile:
```
COPY asound.conf /etc/asound.conf
```
- [via](https://github.com/cypress-io/cypress-docker-images/issues/52#issuecomment-446144630)

So now things seem to work (but now facing unrelated gpu issues, so this is not fully tested).

**Comment by b-ma** [comment]
ok, cool thanks for the informations.

> I'd be happy to make a new build when needed (e.g. for new versions).

Thanks, but I would prefer to not to introduce such step in the build and release process if I can do another way. Is this something you can live with for now, I mean creating the build on your own side?

**Comment by bthj** [comment]
Yes, creating the build on my side is absolutely fine, thanks.

**Comment by b-ma** [comment]
Just re-opening this as it should be fixed at some point

**Comment by b-ma** [comment]
Hey, this should be fixed now, feel free to reopen if you run into troubles 
For information: the arm64 build is made on a RPi, maybe this introduces some incompatibilities with other platform (hopefully not...)
