### ISSUE TITLE
Error using multichannel soundboard with webaudioapi

### ISSUE THREAD

**Issue by etiennedemoulin** [ircam-ismm/node-web-audio-api#23]
Using a Blackhole virtual soundboard (https://github.com/ExistentialAudio/BlackHole) with 256 inputs / outputs

thread '<unnamed>' panicked at 'NotSupportedError - Invalid number of channels: 256 is outside range [1, 32]', /Users/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/web-audio-api-0.31.0/src/render/quantum.rs:307:9
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
fatal runtime error: Rust panics must be rethrown

**Comment by b-ma** [comment]
Heiho,

Damn... this is quite logical as the API only support up to 32 channels (this is in the spec and already quite large, but could be quite easily changed if needed). 
But, in any case I don't really get at which point you got the error, could you share your code? Did you try to explicitly set the number of channels of the audio destination to something supported, e.g. ?

```js
const audioContext = new AudioContext();
audioContext.destination.channelCount = 8;
await audioContext.resume();
```

cf. [channelCount](https://webaudio.github.io/web-audio-api/#dom-audionode-channelcount)

**Comment by etiennedemoulin** [comment]
Coucou, 
No needs for more than 32 channels in my purpose.
In fact, with explicit channel declaration I'm now facing this other error.
thread '<unnamed>' panicked at 'Up-mixing from 1 to 10 channels not supported', /Users/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/web-audio-api-0.31.0/src/render/quantum.rs:576:22

Here is my code 
`  const audioContext = new AudioContext();
  audioContext.destination.channelCount = 32;
  await audioContext.resume();

  const merger = audioContext.createChannelMerger(10); // 8 in, 1 out

  for (let i = 0; i < 10; i++) {
    const engine = new Engine(audioContext, player);
    engine.env.connect(merger, 0, i);
    player.onUpdate(() => {
      $layout.requestUpdate();
      engine.render();
    })
  }

  merger.connect(audioContext.destination);`

**Comment by b-ma** [comment]
Ok looks good (kind of... :)

Actually by default the nodes try to up-mix / down-mix in an automatic way. In your case this is not what you want as you want to control the routing (and there is no automatic rules for up / down mix from 1 to 10 as you can see in the error). 

To disable this behavior you need to set the `channelInterpretation` to `discrete` (cf. https://webaudio.github.io/web-audio-api/#dom-audionode-channelinterpretation)

Then your snippet would become something like:

```js
const audioContext = new AudioContext();
audioContext.destination.channelCount = 10; // if you need only 10 channels, no need to ask for 32
audioContext.destination.channelInterpretation = 'discrete';
await audioContext.resume();

const merger = audioContext.createChannelMerger(10); // 10 in, 1 *mc* out
merger.connect(audioContext.destination);

for (let i = 0; i < 10; i++) {
  const engine = new Engine(audioContext, player);
  engine.env.connect(merger, 0, i);
  // be careful here, if you have only one player your just subscribe 10 times to the updates
  player.onUpdate(() => {
    $layout.requestUpdate();
    engine.render();
  })
}
```

**Comment by b-ma** [comment]
should be fixed in ec28162d005d556f220c76a17ae454f5d9b5f8ca 

Let's confirm everything is ok before closing the issue

**Comment by etiennedemoulin** [comment]
Update on the issue :
ok with a soundboard with maxChannelCount < 32
but with a > 32ch soundboard it throws like this `thread '<unnamed>' panicked at 'NotSupportedError - Invalid number of channels: 256 is outside range [1, 32]', /Users/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/web-audio-api-0.31.0/src/render/quantum.rs:307:9`

**Comment by orottier** [comment]
By design our implementation only supports configurations up to 32 channels.
Supporting more channels brings a performance hit (memory and CPU) unfortunately.

@b-ma what do you think?
I think it is technically possible to make the `RenderThread` const generic over the MAX_CHANNEL_COUNT so we can increase the limit on the fly for users with 32+ channels. This brings the best of both worlds, no performance hit for normal users, flexibility and no added API surface for expert users.
Disadvantage: a lot of engineering and more code to support
Advantage: I'm up for a challenge

**Comment by b-ma** [comment]
Hey Otto,

> I think it is technically possible to make the RenderThread const generic over the MAX_CHANNEL_COUNT so we can increase the limit on the fly for users with 32+ channels. This brings the best of both worlds, no performance hit for normal users, flexibility and no added API surface for expert users.

I was thinking of a kind of compilation variable (if such thing exists :) that we could change without changing the code itself. 
But your solution seems even more more interesting, if you think this is feasible that would be great indeed! Maybe we could even make the default `MAX_CHANNEL_COUNT` lower in such case, because we would still be able to support 32 channels?

But in any case, I think we have a bug because @etiennedemoulin does not use more than 32 channels in his application. The bug occurs just by switching the soundcard without changing actual the code. (Etienne can you confirm I'm not mistaking?) 

There are other related questions that I'm a bit curious about, e.g. what should report [`destination.maxChannelCount`](https://webaudio.github.io/web-audio-api/#dom-audiodestinationnode-maxchannelcount) if the soundcard has 256 channels, the real number or our actual limit (nothing in the spec on that point), what do Chrome and Firefox do, etc.). I will do some more testing tomorrow to dig into all that.

**Comment by etiennedemoulin** [comment]
You're right @b-ma , I don't need more than 32ch in my application
Chrome and Firefox display destination.maxChannelCount at 32 even if the soundboard support more than that.

**Comment by b-ma** [comment]
Thanks! I actually found the issue in the rust crate, should be fixed in some future release

**Comment by b-ma** [comment]
Fixed further with [web-audio-api-rs/issues/320](https://github.com/orottier/web-audio-api-rs/issues/320)

**Comment by etiennedemoulin** [comment]
work for me with 0.12 :) super thx !!!

**Comment by b-ma** [comment]
Cool!
