### ISSUE TITLE
`AudioContext.decodeAudioData` .m4a format not supported?

### ISSUE THREAD

**Issue by luliloveshe** [ircam-ismm/node-web-audio-api#35]
```
import { AudioContext,load } from 'node-web-audio-api';
let arrayBuffer: ArrayBuffer;= load(file);
let audioBuffer: AudioBuffer= await new AudioContext({ sinkId: 'none' }).decodeAudioData(arrayBuffer);
```
Playback is normal using webAduioAPI in the browser.
This file is 7M in size and is in .m4a format

[0dec03f3ccf34906918053b36fe2c2e0.zip](https://github.com/ircam-ismm/node-web-audio-api/files/12644303/0dec03f3ccf34906918053b36fe2c2e0.zip)

**Comment by luliloveshe** [comment]
I used ffmpeg to convert to mp3 and it worked. Maybe the .m4a format is not currently supported.

**Comment by b-ma** [comment]
Hey, several things are going on here:

- Seems that you don't use the latest version of the lib, since the `load` helper has been dropped in [v0.10](https://github.com/ircam-ismm/node-web-audio-api/blob/main/CHANGELOG.md#v0110-21072023) (note that the most recent version is 0.11)
- Since this version, which target `web-audio-api-rs` version v0.32, `.m4a` files should be supported, cf. https://github.com/orottier/web-audio-api-rs/blob/main/CHANGELOG.md#version-0320-2023-07-16. I'm not sure I have already tested it myself but normally it should work.

So maybe try to update the lib to the latest version and adapt your code to use the more compliant `decodeAudioData` introduced in PR https://github.com/ircam-ismm/node-web-audio-api/pull/25:

```js
import fs from 'node:fs';
import { AudioContext } from 'node-web-audio-api';

const audioContext = new AudioContext({ sinkId: 'none' });
const arrayBuffer = fs.readFileSync(filename).buffer;
const audioBuffer = await audioContext.decodeAudioData(arrayBuffer);
```

Note that you should probably avoid using the pattern 
```js
await new AudioContext({ sinkId: 'none' }).decodeAudioData(arrayBuffer);
``` 
It creates a new context each time you decode an audio file, which is just using resources for nothing and could create weird issues if generalized (e.g. nodes created by different contexts cannot be connected with each others). It's best to create one single `AudioContext` and reuse the instance everywhere as in the example above.

**Comment by luliloveshe** [comment]
Thank you very much, I will take a look first and then give feedback.

**Comment by luliloveshe** [comment]
I upgraded to the latest version 0.12.0 and the test passed. Thanks again

**Comment by b-ma** [comment]
Ok cool!
